apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: hello-node
  name: hello-node
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hello-node
    spec:
      containers:
      - image: us.gcr.io/gke-sample-takashi1117/hello-node:v1
        name: hello-node
        ports:
        - containerPort: 8080
